---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Run ara-report role
      include_role:
        name: ara-report

    - name: Run htmlify-logs role
      include_role:
        name: htmlify-logs

    - name: Run Zuul manifest role
      include_role:
        name: generate-zuul-manifest

    - name: Upload logs to swift
      block:
        - name: Run upload-logs-swift role
          include_role:
            name: upload-logs-swift
          vars:
            zuul_log_cloud_config: "{{ vexxhost_clouds_yaml }}"
      rescue:
        # NOTE(pabelanger): If for some reason we cannot upload logs, try
        # again. It is possible network issue on remote side.
        - name: Run upload-logs-swift role
          include_role:
            name: upload-logs-swift
          vars:
            zuul_log_cloud_config: "{{ vexxhost_clouds_yaml }}"

    # NOTE(pabelanger): We should update upload-logs-swift role to accept a
    # zuul_log_url variable so we don't have to do this.
    - name: Setup log path fact
      include_role:
        name: set-zuul-log-path-fact

    - name: Return log URL to Zuul
      zuul_return:
        data:
          zuul:
            log_url: "https://logs.zuul.ansible.com/{{ zuul_log_path }}/"
